name: Integración Continua Python

on:
  push:
    branches: [ main ] # O el nombre de tu rama principal
  pull_request:
    branches: [ main ] # O el nombre de tu rama principal

jobs:
  build: # El nombre del job, puede mantenerse en inglés o traducirse (ej. "construir")
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Usar una versión específica como '3.10' o un rango

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Linting con Flake8
      run: |
        # detener la compilación si hay errores de sintaxis de Python o nombres no definidos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero trata todos los errores como advertencias. El editor de GitHub tiene 127 caracteres de ancho
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Pruebas con unittest
      run: |
        python -m unittest discover tests
